sudo: false
language: node_js
node_js:
    - '13'
cache:
    directories:
        - node_modules
jobs:
  include:
    - stage: build
      script: ./travis/build.js
    - stage: test
      script: ./travis/test.js